### ISSUE TITLE
Client Crash on Fabric 1.21.1 and 0.16.9

### ISSUE THREAD

**Issue by suerion** [Alminoris/ArborealNature#3]
Hey, had again an issue on the from aboreal,

Always on trying to open the inventory, the client crash on my side. Without the mod, it work fine.

Crashlog has no informations ->
[crash-2024-12-24_00.57.02-client.txt](https://github.com/user-attachments/files/18234361/crash-2024-12-24_00.57.02-client.txt)

Only on Crash, this is in the log ->
```
Unreported exception thrown!
java.lang.NullPointerException: null
Negative index in crash report handler (0/7)
```

Latest.log from Client
https://mclo.gs/O4i4oVJ

**Comment by suerion** [comment]
@Alminoris had get an hint,

There is allways an Log Line, that  the item Groups are get not loading

**Comment by Alminoris** [comment]
Did the issue start with version 0.3.0 or earlier versions? In version 0.2.9, I divided the main item group into several for each extension. Perhaps this has something to do with it. But when I tested the mod with my modpack, everything worked fine. Maybe, the main reason of the issue is about conflicting item groups from my mod and others. Try removing a few mods with their own item groups at a time. Also, try this version without adding blocks and items to Minecraft's existing item groups (this was also introduced in version 0.2.9). https://drive.google.com/file/d/1Jy2d32c0nzBrPR1OQ82yYGA3kMdu-vlg/view?usp=sharing

**Comment by suerion** [comment]
Hey, the issue is on the newest 0.3.0 version, 

The latest version 2.9 work fine

**Comment by suerion** [comment]
Hey, i had now an other issue @Alminoris 

With ArborealNature it shows only a few Items in REI anymore 
![2024-12-26_23 31 51](https://github.com/user-attachments/assets/25c4a82b-7179-4cff-aea3-6e9defb70fe2)

Without ArborealNature it gives me Again all sites from REI
![2024-12-26_23 54 14](https://github.com/user-attachments/assets/56a3922e-047b-4b3d-b9f0-e18f5e9271d7)

Don't know from where this get, will look more in the REI logs tomorow

**Comment by Alminoris** [comment]
I usually use EMI, not REI, so I don't know why this is happening. Try the EMI or, as you said, look for REI logs.

**Comment by suerion** [comment]
https://github.com/shedaniel/RoughlyEnoughItems/issues/1785
